### ISSUE TITLE
Runtime error in Feature Extraction

### ISSUE THREAD

**Issue by adthoms** [TixiaoShan/LIO-SAM#194]
Hi @TixiaoShan, I am able to compile LIO-SAM, launch `run.launch` with no errors, and during playback of `casual_walk.bag` I encounter the following error: 

```
[ INFO] [1611676482.395435673]: ----> Feature Extraction Started.
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
```
I checked `master.log` and see the following error (no other errors are present):

```
[rosmaster.threadpool][ERROR] 2021-01-26 10:54:45,107: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault -1: 'publisherUpdate: unknown method name'> 
```
any thoughts on what could be happening? I am using Ros Melodic on Ubuntu 18.04 LTS

**Comment by adthoms** [comment]
issue present in `master.log` appears to be related to ros/ros_comm#572, leading me to believe it has something to do with recent system/ROS updates.
